### ISSUE TITLE
Fatal error on MW 1.29.0

### ISSUE THREAD

**Issue by WouterRademaker** [ProfessionalWiki/Bootstrap#1]
On the ScoutWiki farm we get this error when we update to 1.29 from 1.27 with the extension enabled: "Fatal error: Call to a member function ucfirst() on a non-object in /srv/www/scoutwiki/htdocs-1.29/includes/user/User.php on line 1079" when loged in. And the error  "Fatal error: Call to a member function getCode() on a non-object in /srv/www/scoutwiki/htdocs-1.29/includes/user/User.php on line 1578" when loged out. With all debug options enabled, these are the only lines written, no stack trace. Test on https://uk.scoutwiki.org also errors with no other extensions enabled.

**Comment by s7eph4n** [comment]
Thanks! I will try to find out what's going on. However without further input that will not be easy. The extension seems to be working when loaded by the Chameleon skin, so my current hypothesis is that something breaks when it is loaded on its own.
Could you describe, how exactly you load the extension? Also, could you describe the settings by which you tried to get the stack trace? Because it is the first time that I heard of an error message being produced but no stack trace being available.

**Comment by lloonngg** [comment]
I also presumably have the same problem with MW 1.29.  I have tried installing various versions of the bootstrap extension, including older versions going back to 1.0.  I have also tried installing the chameleon skin on its own which would install the bootstrap dependency.  With the chameleon skin, I tried older versions back to 1.0.  This was all done with composer.  I have the following turned on for debugging:

$wgDebugToolbar = true;
error_reporting( -1 );
ini_set( 'display_errors', 1 );

The page does not load whatsoever and I see no stack trace or php errors.  Only a HTTP ERROR 500 with essentially a blank page.  I can help troubleshoot if you tell me what debugging options to turn on.

~~~~

**Comment by lloonngg** [comment]
After checking my settings a bit more, it turns out that my implementation was incorrect.  I deployed MW 1.29 with the Bootstrap extension and Chameleon skin via Kubernetes and forgot to mount the Bootstrap extension folder from my host drive to the docker container.  I had done this for the skins folder.  After specifying the Bootstrap extension folder as a mount point, both Bootstrap and Chameleon skin are working.  On my system, Bootstrap was installed as a dependency of the Chameleon skin.

**Comment by JeroenDeDauw** [comment]
Please open a new issue if there still is a problem
